server:
  port: 9090

calculator:
  classic:
    recordsSize: 2

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS
